###########################################################################################
#     _____                 _       _   _____     _                 _                     #
#    /  __ \               (_)     | | |  ___|   | |               (_)                    #
#    | /  \/_ __ _   _  ___ _  __ _| | | |____  _| |_ ___ _ __  ___ _  ___  _ __  ___     #
#    | |   | '__| | | |/ __| |/ _` | | |  __\ \/ / __/ _ \ '_ \/ __| |/ _ \| '_ \/ __|    #
#    | \__/\ |  | |_| | (__| | (_| | | | |___>  <| ||  __/ | | \__ \ | (_) | | | \__ \    #
#    \____/_|   \__,_|\___|_|\__,_|_| \____/_/\_\\__\___|_| |_|___/_|\___/|_| |_|___/     #
###########################################################################################

############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# Here you can change all the configurations for this plugin
#
# Each option will have its own description and an example to help you out
# and at the bottom of this file are some useful variables and symbols
# - colour codes
# - formatting codes


############################################################
# +------------------------------------------------------+ #
# |             Crucial Extensions (Global)              | #
# +------------------------------------------------------+ #
############################################################

# Change the message that is displayed when a user joins
# Use {PLAYER} to use the player's name
# Use Minecraft colour codes to change the colour
# leave blank for no message
# Example: '§2Oh look! §6{PLAYER} §2joined the server!'
join-message: ''

# Change the message that is displayed when a user leaves
# Use {PLAYER} to use the player's name
# Use Minecraft colour codes to change the colour
# leave blank for no message
# Example: '§2Goodbye §6{PLAYER} §2!'
leave-message: ''

# Change the message that is displayed when the chat is cleared
# Use {PLAYER} to use the player's name
# Use Minecraft colour codes to change the colour
# leave blank for no message
# Example: '§2Chat cleared by §6{PLAYER}§2, thanks!'
chat-clear-message: ''


#####################################################################################
#  Colors                                                                           #
#    (Minecraft Name)	          Chat Code MOTD Code	Decimal	    Hexadecimal     #
#    Dark Red (dark_red)	      §4	    \u00A74	    11141120	AA0000          #
#    Red (red)	                  §c	    \u00A7c	    16733525	FF5555          #
#    Gold (gold)	              §6	    \u00A76	    16755200	FFAA00          #
#    Yellow (yellow)	          §e	    \u00A7e	    16777045	FFFF55          #
#    Dark Green (dark_green)      §2	    \u00A72	    43520	    00AA00          #
#    Green (green)	              §a	    \u00A7a	    5635925	    55FF55          #
#    Aqua (aqua)	              §b	    \u00A7b	    5636095	    55FFFF          #
#    Dark Aqua (dark_aqua)	      §3	    \u00A73	    43690	    00AAAA          #
#    Dark Blue (dark_blue)	      §1	    \u00A71	    170         0000AA          #
#    Blue (blue)	              §9	    \u00A79	    5592575	    5555FF          #
#    Light Purple (light_purple)  §d	    \u00A7d	    16733695	FF55FF          #
#    Dark Purple (dark_purple)	  §5	    \u00A75	    11141290	AA00AA          #
#    White (white)	              §f	    \u00A7f	    16777215	FFFFFF          #
#    Gray (gray)	              §7	    \u00A77	    11184810	AAAAAA          #
#    Dark Gray (dark_gray)	      §8	    \u00A78	    5592405	    555555          #
#    Black (black)	              §0	     \u00A70	0	        000000          #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   Formats                                                                         #
#     Description	          Chat Code	MOTD Code                                   #
#     Obfuscated	          §k        \u00A7k                                     #
#     Bold	                  §l	    \u00A7l                                     #
#     Strikethrough	          §m	    \u00A7m                                     #
#     Underline	              §n	    \u00A7n                                     #
#     Italic	              §o	    \u00A7o                                     #
#     Reset the default color §r	    \u00A7r                                     #
#####################################################################################