name: CrucialExtension
version: ${project.version}
main: me.inanis.plugins.crucialextension.CrucialExtension
api-version: 1.16
authors: [ Inanis ]
description: A Minecraft Java Plugin for 1.16 bukkit-based servers as a light-weight alternative to Essentials
#softdepend: [PlaceholderAPI] # This is used, if your plugin works without PlaceholderAPI.
#depend: [PlaceholderAPI] # If your plugin requires PlaceholderAPI, to work, use this.


commands:
  heal:
    description: Back up to full health
    usage: /<command> [player]

  feed:
    description: Back up to full hunger
    usage: /<command> [player]

  god:
    description: Toggle invincibility
    usage: /<command>

  fly:
    description: Start flying!
    usage: /<command>

  vault:
    description: Open a personal vault
    usage: /<command>
    aliases: [ pv ]

  vanish:
    description: Hide yourself from everyone
    usage: /<command> [player]
    aliases: [v]

  whisper:
    description: Send a private message to a player
    usage: /<command> player message
    aliases: [ w, pm, privatemessage ]

  clearchat:
    description: Clears the chat by sending blank lines
    usage: /<command>
    aliases: [ cleanchat ]

  kit:
    description: Get a kit
    usage: /<command> [name] [player]

  gmsp:
    description: Gamemode spectator
    usage: /<command> [player]